export const TAKE_ALL_AUDITORIES = "TAKE_ALL_AUDITORIES"
export const UPDATE_AUDITORIES = "TAKE_ALL_AUDITORIES"
export const GET_AUDITORIES = "GET_AUDITORIES"
export const SET_AUDITORIES = "GET_AUDITORIES"
